import type { AgeBand } from "./models";

export type TrainingTemplate = {
  id: string;
  title: string;
  ageBands: AgeBand[];
  tags: string[];
  warmup: string[];
  main: string[];
  cooldown: string[];
  warmupTime: string;
  mainTime: string;
  cooldownTime: string;
};

export const trainingTemplates: TrainingTemplate[] = [
  {
    id: "mini-2x2-fundamentos",
    title: "Mini 2x2 - habilidades motoras e toque",
    ageBands: ["8-9"],
    tags: ["ludico", "fundamentos", "toque", "saque por baixo", "jogo reduzido"],
    warmup: [
      "Jogo ludico de corrida e saltos com bola",
      "Quicar, lancar e receber em duplas",
      "Toque alto estacionario (controle)",
    ],
    main: [
      "Progressao 1x1: saque por baixo + toque",
      "2x2 com regra: sem bloqueio e sem tocar na rede",
      "Construcao do jogo com toque e largada",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "10'",
    mainTime: "35'",
    cooldownTime: "5'",
  },
  {
    id: "mini-2x2-saque",
    title: "Mini 2x2 - saque e construcao do jogo",
    ageBands: ["8-9"],
    tags: ["saque por baixo", "construcao do jogo", "fundamentos"],
    warmup: [
      "Brincadeira de alvo com saque por baixo",
      "Passe em circulo com toque",
    ],
    main: [
      "Sequencia saque -> recepcao -> levantamento",
      "2x2 com rodizio simples",
      "Jogo curto com pontos por 3 toques",
    ],
    cooldown: ["Alongamento leve", "Respiracao guiada"],
    warmupTime: "10'",
    mainTime: "35'",
    cooldownTime: "5'",
  },
  {
    id: "mini-3x3-cooperacao",
    title: "Mini 3x3 - cooperacao e manchete",
    ageBands: ["10-12"],
    tags: ["cooperacao", "manchete", "toque", "saque por baixo"],
    warmup: [
      "Roda de toque com deslocamento",
      "Jogo cooperativo 3x3 com toques",
    ],
    main: [
      "Aperfeicoar saque por baixo e toque",
      "Introducao a manchete e cobertura",
      "Jogo 3x3 com organizacao e rotacao simples",
    ],
    cooldown: ["Alongamento leve", "Respiracao e foco"],
    warmupTime: "10'",
    mainTime: "40'",
    cooldownTime: "5'",
  },
  {
    id: "mini-3x3-defesa",
    title: "Mini 3x3 - largada e defesa",
    ageBands: ["10-12"],
    tags: ["largada", "defesa", "jogo reduzido"],
    warmup: [
      "Controle de bola em pares (toque/manchete)",
      "Mobilidade geral e coordenacao",
    ],
    main: [
      "Largada e ataque leve",
      "Defesa basica com direcionamento",
      "Jogo 3x3 com sequencia de acoes",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "10'",
    mainTime: "40'",
    cooldownTime: "5'",
  },
  {
    id: "mini-4x4-transicao",
    title: "Mini 4x4 - transicao e regras basicas",
    ageBands: ["13-15"],
    tags: ["transicao", "cortada", "bloqueio", "regras basicas"],
    warmup: [
      "Passe com deslocamento (toque/manchete)",
      "Saque por baixo em alvos",
    ],
    main: [
      "Aperfeicoar cortada e bloqueio (posicionamento)",
      "Recepcao e defesa com tres jogadores",
      "Jogo 4x4 com ataque pela entrada e saida",
    ],
    cooldown: ["Alongamento leve", "Respiracao guiada"],
    warmupTime: "10'",
    mainTime: "45'",
    cooldownTime: "5'",
  },
  {
    id: "mini-4x4-defesa",
    title: "Mini 4x4 - sistema de defesa 1x3",
    ageBands: ["13-15"],
    tags: ["defesa", "sistema 1x3", "organizacao"],
    warmup: [
      "Toque e manchete com deslocamento",
      "Jogo reduzido de reacao",
    ],
    main: [
      "Sistema de defesa 1x3 por leitura",
      "Defesa com quedas e rolamentos leves",
      "Jogo 4x4 com rotacao simples",
    ],
    cooldown: ["Alongamento leve", "Roda de fechamento"],
    warmupTime: "10'",
    mainTime: "45'",
    cooldownTime: "5'",
  },
  {
    id: "cmv-6-7-10bal",
    title: "CMV 6-7 - 10-bal e habilidades basicas",
    ageBands: ["8-9"],
    tags: ["cmv", "10-bal", "ludico", "controle"],
    warmup: [
      "Baltikkertje (pega-pega com bola)",
      "Rolar e mirar em alvos",
    ],
    main: [
      "10-bal nivel 2 (controle e precisao)",
      "Gooien e vangen level 1",
      "Balparcours com quicar e lancar",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "10'",
    mainTime: "30'",
    cooldownTime: "5'",
  },
  {
    id: "cmv-6-7-toque",
    title: "CMV 6-7 - toque e saque por baixo",
    ageBands: ["8-9"],
    tags: ["cmv", "toque", "saque por baixo", "ludico"],
    warmup: [
      "Bovenhands mikken (toque em alvos)",
      "Gooien e vangen level 2",
    ],
    main: [
      "Toetsen level 1 (toque controlado)",
      "Onderarms opslaan (saque por baixo) contra a parede",
      "Lijnen tikken (jogo de linhas)",
    ],
    cooldown: ["Respiracao guiada", "Alongamento leve"],
    warmupTime: "10'",
    mainTime: "30'",
    cooldownTime: "5'",
  },
  {
    id: "cmv-8-10-recepcao",
    title: "CMV 8-10 - recepcao e toque",
    ageBands: ["10-12"],
    tags: ["cmv", "recepcao", "toque", "controle"],
    warmup: [
      "Opslaan en vangen (saque e recepcao)",
      "Balparcours com deslocamento",
    ],
    main: [
      "Toetsen level 2 (toque com alvo)",
      "Gooien en toetsen (jogo de passe e toque)",
      "CMV nivel 2 com tres toques",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "10'",
    mainTime: "35'",
    cooldownTime: "5'",
  },
  {
    id: "cmv-8-10-smashbal",
    title: "CMV 8-10 - smashbal e ataque leve",
    ageBands: ["10-12"],
    tags: ["cmv", "smashbal", "ataque", "coordenacao"],
    warmup: [
      "Hoge ballen vangen (bola alta)",
      "Estafette com bola",
    ],
    main: [
      "Smashbal level 1 (batida leve)",
      "Opslaan en toetsen (saque + toque)",
      "CMV nivel 3 com rodizio simples",
    ],
    cooldown: ["Respiracao guiada", "Alongamento leve"],
    warmupTime: "10'",
    mainTime: "35'",
    cooldownTime: "5'",
  },
  {
    id: "cmv-11-12-toque",
    title: "CMV 11-12 - toque e jogo 3x",
    ageBands: ["13-15"],
    tags: ["cmv", "toque", "jogo", "organizacao"],
    warmup: [
      "Bovenhands spelen contra a parede",
      "Opslaan em alvos",
    ],
    main: [
      "Toetsen level 3 (toque avancado)",
      "3 keer spelen (sequencia de 3 toques)",
      "CMV nivel 4 com foco em organizacao",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "10'",
    mainTime: "40'",
    cooldownTime: "5'",
  },
  {
    id: "cmv-11-12-ataque",
    title: "CMV 11-12 - ataque e saque",
    ageBands: ["13-15"],
    tags: ["cmv", "ataque", "saque", "defesa"],
    warmup: [
      "Hoge ballen vangen (bola alta)",
      "Estafette com saque por baixo",
    ],
    main: [
      "Smashbal level 1 (ataque controlado)",
      "Opslaan en toetsen (saque + toque)",
      "CMV nivel 5 com jogo reduzido",
    ],
    cooldown: ["Respiracao guiada", "Alongamento leve"],
    warmupTime: "10'",
    mainTime: "40'",
    cooldownTime: "5'",
  },
  {
    id: "warmup-volleyveilig",
    title: "VolleyVeilig - aquecimento preventivo",
    ageBands: ["8-9", "10-12", "13-15"],
    tags: ["aquecimento", "prevencao", "agilidade", "estabilidade"],
    warmup: [
      "Corrida leve com mudanca de direcao",
      "Alongamento dinamico (ombro, quadril, tornozelo)",
      "Agilidade e reacao com comandos curtos",
    ],
    main: [
      "Estabilidade de ombro com bola (toque controlado)",
      "Equilibrio dinamico em apoio unilateral",
      "Sequencia tecnica leve: toque, manchete e saque",
    ],
    cooldown: ["Respiracao guiada", "Alongamento leve"],
    warmupTime: "12'",
    mainTime: "30'",
    cooldownTime: "5'",
  },
  {
    id: "mini-games-1x1-2x2",
    title: "Jogos base 1x1 e 2x2",
    ageBands: ["8-9"],
    tags: ["jogo", "ludico", "controle", "iniciacao"],
    warmup: [
      "Brincadeira de alvo com bola",
      "Quicar e lancar em duplas",
    ],
    main: [
      "Jogo 1x1 com regra de 1 toque",
      "Jogo 2x2 com saque por baixo",
      "Pontos extras por manter a bola viva",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "10'",
    mainTime: "25'",
    cooldownTime: "5'",
  },
  {
    id: "recepcao-basica",
    title: "Recepcao basica e passe",
    ageBands: ["8-9", "10-12"],
    tags: ["recepcao", "passe", "controle"],
    warmup: [
      "Bola alta para agarrar e devolver",
      "Toque estacionario em alvo",
    ],
    main: [
      "Recepcao com manchete (curta e longa)",
      "Passe para alvo fixo",
      "Jogo reduzido com regra de 2 toques",
    ],
    cooldown: ["Respiracao guiada", "Alongamento leve"],
    warmupTime: "10'",
    mainTime: "30'",
    cooldownTime: "5'",
  },
  {
    id: "saque-precisao",
    title: "Saque por baixo e alvos",
    ageBands: ["10-12", "13-15"],
    tags: ["saque", "precisao", "controle"],
    warmup: [
      "Mobilidade de ombro e punho",
      "Saque leve sem alvo",
    ],
    main: [
      "Saque por baixo em zonas definidas",
      "Saque em sequencia com pontuacao",
      "Jogo reduzido iniciando sempre com saque",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "8'",
    mainTime: "30'",
    cooldownTime: "5'",
  },
  {
    id: "toque-levantamento",
    title: "Toque e levantamento",
    ageBands: ["10-12", "13-15"],
    tags: ["toque", "levantamento", "controle"],
    warmup: [
      "Toque em duplas com deslocamento",
      "Toque alto para controle",
    ],
    main: [
      "Levantamento frontal com alvo",
      "Levantamento apos recepcao",
      "Jogo 3x3 com foco em 3 toques",
    ],
    cooldown: ["Respiracao guiada", "Alongamento leve"],
    warmupTime: "10'",
    mainTime: "35'",
    cooldownTime: "5'",
  },
  {
    id: "ataque-transicao",
    title: "Ataque e transicao simples",
    ageBands: ["13-15"],
    tags: ["ataque", "transicao", "jogo"],
    warmup: [
      "Aquecimento tecnico com manchete e toque",
      "Sequencia curta de passos de ataque",
    ],
    main: [
      "Ataque controlado em zonas",
      "Transicao defesa-ataque em duplas",
      "Jogo reduzido com foco em contra-ataque",
    ],
    cooldown: ["Alongamento leve", "Roda de fechamento"],
    warmupTime: "10'",
    mainTime: "40'",
    cooldownTime: "5'",
  },
  {
    id: "bloqueio-defesa",
    title: "Bloqueio e defesa",
    ageBands: ["13-15"],
    tags: ["bloqueio", "defesa", "posicionamento"],
    warmup: [
      "Mobilidade e salto leve",
      "Defesa baixa com reacao",
    ],
    main: [
      "Bloqueio simples com foco em bracos",
      "Defesa em 1x3 por leitura",
      "Jogo reduzido com foco em defesa",
    ],
    cooldown: ["Respiracao guiada", "Alongamento leve"],
    warmupTime: "10'",
    mainTime: "40'",
    cooldownTime: "5'",
  },
  {
    id: "rotacao-5x1",
    title: "Rotacao 5x1 e organizacao",
    ageBands: ["13-15"],
    tags: ["tatico", "rotacao", "5x1"],
    warmup: [
      "Passe e toque em circulo",
      "Saque leve por zona",
    ],
    main: [
      "Mapa de rotacao 5x1 com posicoes",
      "Entrada e saida do libero (simulacao)",
      "Jogo reduzido com rodizio a cada ponto",
    ],
    cooldown: ["Alongamento leve", "Roda de feedback rapido"],
    warmupTime: "8'",
    mainTime: "40'",
    cooldownTime: "5'",
  },
];
